#----------------------------------------------------------------
# Generated CMake target import file for configuration "Release".
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Import target "TKDE" for configuration "Release"
set_property(TARGET TKDE APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKDE PROPERTIES
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/libTKDE.so.7.8.1"
  IMPORTED_SONAME_RELEASE "libTKDE.so.7.8"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKDE )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKDE "${_IMPORT_PREFIX}/lib/libTKDE.so.7.8.1" )

# Import target "TKXSBase" for configuration "Release"
set_property(TARGET TKXSBase APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKXSBase PROPERTIES
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/libTKXSBase.so.7.8.1"
  IMPORTED_SONAME_RELEASE "libTKXSBase.so.7.8"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKXSBase )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKXSBase "${_IMPORT_PREFIX}/lib/libTKXSBase.so.7.8.1" )

# Import target "TKDESTEP" for configuration "Release"
set_property(TARGET TKDESTEP APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKDESTEP PROPERTIES
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/libTKDESTEP.so.7.8.1"
  IMPORTED_SONAME_RELEASE "libTKDESTEP.so.7.8"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKDESTEP )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKDESTEP "${_IMPORT_PREFIX}/lib/libTKDESTEP.so.7.8.1" )

# Import target "TKXCAF" for configuration "Release"
set_property(TARGET TKXCAF APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKXCAF PROPERTIES
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/libTKXCAF.so.7.8.1"
  IMPORTED_SONAME_RELEASE "libTKXCAF.so.7.8"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKXCAF )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKXCAF "${_IMPORT_PREFIX}/lib/libTKXCAF.so.7.8.1" )

# Import target "TKDEIGES" for configuration "Release"
set_property(TARGET TKDEIGES APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKDEIGES PROPERTIES
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/libTKDEIGES.so.7.8.1"
  IMPORTED_SONAME_RELEASE "libTKDEIGES.so.7.8"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKDEIGES )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKDEIGES "${_IMPORT_PREFIX}/lib/libTKDEIGES.so.7.8.1" )

# Import target "TKDESTL" for configuration "Release"
set_property(TARGET TKDESTL APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKDESTL PROPERTIES
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/libTKDESTL.so.7.8.1"
  IMPORTED_SONAME_RELEASE "libTKDESTL.so.7.8"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKDESTL )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKDESTL "${_IMPORT_PREFIX}/lib/libTKDESTL.so.7.8.1" )

# Import target "TKDEVRML" for configuration "Release"
set_property(TARGET TKDEVRML APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKDEVRML PROPERTIES
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/libTKDEVRML.so.7.8.1"
  IMPORTED_SONAME_RELEASE "libTKDEVRML.so.7.8"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKDEVRML )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKDEVRML "${_IMPORT_PREFIX}/lib/libTKDEVRML.so.7.8.1" )

# Import target "TKRWMesh" for configuration "Release"
set_property(TARGET TKRWMesh APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKRWMesh PROPERTIES
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/libTKRWMesh.so.7.8.1"
  IMPORTED_SONAME_RELEASE "libTKRWMesh.so.7.8"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKRWMesh )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKRWMesh "${_IMPORT_PREFIX}/lib/libTKRWMesh.so.7.8.1" )

# Import target "TKDECascade" for configuration "Release"
set_property(TARGET TKDECascade APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKDECascade PROPERTIES
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/libTKDECascade.so.7.8.1"
  IMPORTED_SONAME_RELEASE "libTKDECascade.so.7.8"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKDECascade )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKDECascade "${_IMPORT_PREFIX}/lib/libTKDECascade.so.7.8.1" )

# Import target "TKBinXCAF" for configuration "Release"
set_property(TARGET TKBinXCAF APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKBinXCAF PROPERTIES
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/libTKBinXCAF.so.7.8.1"
  IMPORTED_SONAME_RELEASE "libTKBinXCAF.so.7.8"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKBinXCAF )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKBinXCAF "${_IMPORT_PREFIX}/lib/libTKBinXCAF.so.7.8.1" )

# Import target "TKXmlXCAF" for configuration "Release"
set_property(TARGET TKXmlXCAF APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKXmlXCAF PROPERTIES
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/libTKXmlXCAF.so.7.8.1"
  IMPORTED_SONAME_RELEASE "libTKXmlXCAF.so.7.8"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKXmlXCAF )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKXmlXCAF "${_IMPORT_PREFIX}/lib/libTKXmlXCAF.so.7.8.1" )

# Import target "TKDEOBJ" for configuration "Release"
set_property(TARGET TKDEOBJ APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKDEOBJ PROPERTIES
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/libTKDEOBJ.so.7.8.1"
  IMPORTED_SONAME_RELEASE "libTKDEOBJ.so.7.8"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKDEOBJ )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKDEOBJ "${_IMPORT_PREFIX}/lib/libTKDEOBJ.so.7.8.1" )

# Import target "TKDEGLTF" for configuration "Release"
set_property(TARGET TKDEGLTF APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKDEGLTF PROPERTIES
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/libTKDEGLTF.so.7.8.1"
  IMPORTED_SONAME_RELEASE "libTKDEGLTF.so.7.8"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKDEGLTF )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKDEGLTF "${_IMPORT_PREFIX}/lib/libTKDEGLTF.so.7.8.1" )

# Import target "TKDEPLY" for configuration "Release"
set_property(TARGET TKDEPLY APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKDEPLY PROPERTIES
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/libTKDEPLY.so.7.8.1"
  IMPORTED_SONAME_RELEASE "libTKDEPLY.so.7.8"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKDEPLY )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKDEPLY "${_IMPORT_PREFIX}/lib/libTKDEPLY.so.7.8.1" )

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
